import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../../src/components/shared/header/Header'
import CreateProjects from '../../src/components/createProject/CreateProjects'
// import Home from '../src/components/home/Home'

const CreateProjectsPage: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Crear Proyecto | XP Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CreateProjects/>
    </div>
  )
}

export default CreateProjectsPage
