import type { NextPage } from 'next'
import Head from 'next/head'
import Backlog from '../../src/components/backlog/Backlog'
import Header from '../../src/components/shared/header/Header'

const BacklogPage: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Backlog | XP Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Backlog />
    </div>
  )
}

export default BacklogPage
