import type { NextPage } from 'next'
import Head from 'next/head'
import Home from '../src/components/home/Home'
import Header from '../src/components/shared/header/Header'

const HomePage: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Inicio | XP Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
    </div>
  )
}

export default HomePage
